[Metadata]
Name=PPB - Variables
Author=Dogbert
Version=0.0.1

[Variables]
Font=metropolis
;Font=Anka/Coder


--- Colors ---
white=255, 255, 255
black=0,0,0
gradientOne=235,99,255
gradientTwo=145,104,421
gradientThree=26,206,223
mouseOver=140,140,140


## NOTE TO USERS: If the filepath does not contain any quotation marks, input the filepath like so: "filepath"
## so if the filepath already has quotes, it would look like this: ""C://path""

--- Application Variables ---
App1Path=
App1Icon=#@#Icons\app.png
App1Color=26,206,223

App2Path=
App2Icon=#@#Icons\app.png
App2Color=26,206,223

App3Path= 
App3Icon=#@#Icons\app.png
App3Color=56,181,273

App4Path=
App4Icon=#@#Icons\app.png
App4Color=86,155,322

App5Path=
App5Icon=#@#Icons\app.png
App5Color=115,130,372

App6Path=
App6Icon=#@#Icons\app.png
App6Color=145,104,421

App7Path=
App7Icon=#@#Icons\app.png
App7Color=175,102,366

App8Path=
App8Icon=#@#Icons\app.png
App8Color=196,101,326

App9Path=
App9Icon=#@#Icons\app.png
App9Color=235,99,255

App10Path=
App10Icon=#@#Icons\app.png
App10Color=235,99,255


## NOTE TO USERS: ex filepath for Valorant: ""D:\Games\Riot Games\Riot Client\RiotClientServices.exe" --launch-product=valorant --launch-patchline=live" ##

--- Game Variables ---
Game1Path=
Game1Image=#@#Images\generic.jpg

Game2Path=
Game2Image=#@#Images\generic.jpg

Game3Path=
Game3Image=#@#Images\generic.jpg

Game4Path=
Game4Image=#@#Images\generic.jpg

Game5Path=
Game5Image=#@#Images\generic.jpg

Game6Path=
Game6Image=#@#Images\generic.jpg


--- Storage Drive Variables
Drive1=C:
Drive2=D:
