[Metadata]
Name=PPB - Variables
Author=Dogbert
Version=0.0.1

[Variables]
Font=Anka/Coder

## NOTE TO USERS: If the filepath does not contain any quotation marks, input the filepath like so: "filepath"
## so if the filepath already has quotes, it would look like this: ""C://path""

--- Application Variables ---
App1Path=
App2Path=
App3Path=
App4Path=
App5Path=
App6Path=
App7Path=
App8Path=
App9Path=
App10Path=


## NOTE TO USERS: ex filepath for Valorant: ""D:\Games\Riot Games\Riot Client\RiotClientServices.exe" --launch-product=valorant --launch-patchline=live" ##

--- Game Variables ---
Game1Path=
Game1Image=#@#Images\generic.jpg

Game2Path=
Game2Image=#@#Images\generic.jpg

Game3Path=
Game3Image=#@#Images\generic.jpg

Game4Path=
Game4Image=#@#Images\generic.jpg

Game5Path=
Game5Image=#@#Images\generic.jpg

Game6Path=
Game6Image=#@#Images\generic.jpg


--- Colors ---
white=255,255,255
black=0,0,0
mouseOver=140,140,140
background=40,42,54

