[Metadata]
Name=Variables
Author=Dogbert
Version=0.0.1

[Variables]
Font=Anka/Coder

## NOTE TO USERS: If the filepath does not contain any quotation marks, input the filepath like so: "filepath"
## so if the filepath already has quotes, it would look like this: ""C://path""
--- Application Variables ---
App1Path="C:\Users\Michael\AppData\Local\Discord\Update.exe --processStart Discord.exe"
App2Path=
App3Path=
App4Path=
App5Path=



--- Game Variables ---
Game1Path=
Game1Image=C:\Users\Michael\Documents\Rainmeter\Skins\bert\@Resources\Images\generic.jpg

Game2Path=
Game2Image=C:\Users\Michael\Documents\Rainmeter\Skins\bert\@Resources\Images\generic.jpg

Game3Path=
Game3Image=C:\Users\Michael\Documents\Rainmeter\Skins\bert\@Resources\Images\generic.jpg

Game4Path=
Game4Image=C:\Users\Michael\Documents\Rainmeter\Skins\bert\@Resources\Images\generic.jpg

Game5Path=
Game5Image=C:\Users\Michael\Documents\Rainmeter\Skins\bert\@Resources\Images\generic.jpg

Game6Path=
Game6Image=C:\Users\Michael\Documents\Rainmeter\Skins\bert\@Resources\Images\generic.jpg

Game7Path=
Game7Image=

Game8Path=
Game8Image=

Game9Path=
Game9Image=


--- Colors ---
white=255,255,255
black=0,0,0
mouseOver=140,140,140
background=40,42,54

